# Generated by Django 2.1.5 on 2019-01-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentiments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysispending',
            name='text',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
