# Generated by Django 2.1.5 on 2019-01-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentiments', '0002_analysispending_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysispending',
            name='mean',
        ),
        migrations.AddField(
            model_name='analysis',
            name='mean',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
