# Generated by Django 2.1.5 on 2019-01-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentiments', '0003_auto_20190107_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysispending',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
