# Generated by Django 2.1.5 on 2019-01-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentiments', '0006_analysis_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='best',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='mean',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='median',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='std',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='worst',
            field=models.FloatField(default=0),
        ),
    ]
