# Generated by Django 2.1.5 on 2019-01-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentiments', '0007_auto_20190112_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneDayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('mean', models.FloatField(default=0)),
                ('median', models.FloatField(default=0)),
                ('worst', models.FloatField(default=0)),
                ('best', models.FloatField(default=0)),
                ('std', models.FloatField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentiments.Analysis')),
            ],
        ),
    ]
