# Generated by Django 2.1.5 on 2019-01-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentiments', '0008_onedayresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedayresult',
            name='date',
            field=models.DateField(),
        ),
    ]
