# Generated by Django 2.1.5 on 2019-01-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentiments', '0009_auto_20190123_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=200)),
                ('consumer_secret', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('access_token_secret', models.CharField(max_length=200)),
            ],
        ),
    ]
