# Generated by Django 2.1.5 on 2019-01-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentiments', '0010_twitterauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterauth',
            name='error',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
